#!/usr/bin/env ruby

puts 'loading Rails...'
require File.dirname(__FILE__) + '/../config/environment'

require 'serialport'

sp = SerialPort.new "/dev/tty.usbserial-A7006vDu"

while true
  foo = sp.gets
  puts foo
  foo.chomp!
  if e = LogEvent.parse(foo)
    puts e.inspect
    if e.save
      puts "#{e.class.to_s} #{e.id} saved"
    else
      puts e.errors.full_messages
    end
  end
end
