#!/usr/bin/env ruby

puts 'loading Rails...'
require File.dirname(__FILE__) + '/../config/environment'

require 'serialport'

sp = SerialPort.new "/dev/tty.usbserial-A6005v1G"
puts "ready and listening"

while true
  foo = sp.gets
  puts foo
  foo.chomp!
  if e = LogEvent.parse(foo)
    puts e.inspect
    if e.save
      md = foo.match(/:([^:]+)$/)
      ack = "R:#{md[1]}"
      sp.puts(ack)
      puts "#{e.class.to_s} #{e.id} saved"
    else
      puts e.errors.full_messages
    end
  end
end
